"""Standardized event definitions for LeetCode Auto Sync telemetry."""

from __future__ import annotations

from enum import Enum


class SyncEvent(str, Enum):
    SYNC_STARTED = "SYNC_STARTED"
    METADATA_FETCH_STARTED = "METADATA_FETCH_STARTED"
    METADATA_FETCH_COMPLETED = "METADATA_FETCH_COMPLETED"
    CACHE_HIT = "CACHE_HIT"
    CACHE_MISS = "CACHE_MISS"
    FILES_GENERATED = "FILES_GENERATED"
    FILES_UPDATED = "FILES_UPDATED"
    FILES_SKIPPED = "FILES_SKIPPED"
    README_GENERATED = "README_GENERATED"
    TOPIC_PAGE_UPDATED = "TOPIC_PAGE_UPDATED"
    ROOT_README_UPDATED = "ROOT_README_UPDATED"
    GIT_STAGE_COMPLETED = "GIT_STAGE_COMPLETED"
    GIT_COMMIT_CREATED = "GIT_COMMIT_CREATED"
    GIT_PUSH_COMPLETED = "GIT_PUSH_COMPLETED"
    SYNC_COMPLETED = "SYNC_COMPLETED"
    SYNC_FAILED = "SYNC_FAILED"
