"""Detailed documentation template with comprehensive metadata tables and stats."""

from __future__ import annotations

from typing import Sequence

from config.config_manager import DocumentationConfig
from ..badges import (
    difficulty_indicator,
    difficulty_shields_badge,
    language_fence,
    language_shields_badge,
)
from ..markdown import code_fence, markdown_link, table, unordered_list
from ..models import ProblemMetadata, RepositoryStatistics
from .base import BaseTemplate


class DetailedTemplate(BaseTemplate):
    """Detailed template providing structured metadata tables, hints, and rich breakdowns."""

    def generate_problem_readme(
        self,
        metadata: ProblemMetadata,
        solution: str,
        config: DocumentationConfig,
    ) -> str:
        lines: list[str] = [
            f"# Problem {metadata.problem_number}: {metadata.title}",
            "",
        ]

        badges: list[str] = []
        if config.difficulty_badges:
            badges.append(difficulty_shields_badge(metadata.difficulty))
        if config.language_badges:
            badges.append(language_shields_badge(metadata.language))

        if badges:
            lines.append("\n\n".join(badges))
            lines.append("")

        lines.append("## Metadata Summary")
        lines.append("")

        meta_rows = [
            ("Problem Number", str(metadata.problem_number)),
            ("Title", metadata.title),
            ("Difficulty", metadata.difficulty),
            ("Language", metadata.language),
            ("LeetCode Link", markdown_link(metadata.url, metadata.url)),
        ]

        if config.show_acceptance and metadata.acceptance_rate:
            meta_rows.append(("Acceptance Rate", metadata.acceptance_rate))
        if config.show_likes and metadata.likes is not None:
            meta_rows.append(("Likes", str(metadata.likes)))
        if config.show_dislikes and metadata.dislikes is not None:
            meta_rows.append(("Dislikes", str(metadata.dislikes)))
        if config.show_topics and metadata.topics:
            meta_rows.append(("Topics", ", ".join(metadata.topics)))
        if config.show_companies and metadata.companies:
            meta_rows.append(("Companies", ", ".join(metadata.companies)))

        lines.append(table(("Attribute", "Details"), meta_rows))
        lines.append("")

        if config.show_hints and metadata.hints:
            lines.append("## Hints & Strategy")
            lines.append("")
            lines.append(unordered_list(metadata.hints))
            lines.append("")

        if config.show_solution:
            lines.append("## Implementation Solution")
            lines.append("")
            lines.append(code_fence(solution, language_fence(metadata.language)))
            lines.append("")

        if config.show_timestamp:
            lines.append("---")
            lines.append(f"**Generated by LeetCode Auto Sync** | Last Updated: {metadata.generated_at}")

        return "\n".join(lines).rstrip() + "\n"

    def generate_root_readme(
        self,
        problems: Sequence[ProblemMetadata],
        statistics: RepositoryStatistics,
        config: DocumentationConfig,
    ) -> str:
        lines: list[str] = [
            "# LeetCode Solutions Dashboard",
            "",
            "## Overview & Key Performance Metrics",
            "",
            table(
                ("Metric", "Total Count"),
                [
                    ("Total Problems Solved", statistics.total_solved),
                    ("Easy Problems", statistics.easy_solved),
                    ("Medium Problems", statistics.medium_solved),
                    ("Hard Problems", statistics.hard_solved),
                ],
                align_right={1},
            ),
            "",
        ]

        if config.show_timestamp:
            lines.append(f"**Dashboard Updated**: {statistics.generated_at}")
            lines.append("")

        lines.append("## Difficulty Breakdown")
        lines.append("")
        lines.append(
            table(
                ("Difficulty", "Solved Count", "Percentage"),
                [
                    ("🟢 Easy", statistics.easy_solved, f"{(statistics.easy_solved / max(statistics.total_solved, 1)) * 100:.1f}%"),
                    ("🟠 Medium", statistics.medium_solved, f"{(statistics.medium_solved / max(statistics.total_solved, 1)) * 100:.1f}%"),
                    ("🔴 Hard", statistics.hard_solved, f"{(statistics.hard_solved / max(statistics.total_solved, 1)) * 100:.1f}%"),
                ],
                align_right={1, 2},
            )
        )
        lines.append("")

        lines.append("## Programming Languages")
        lines.append("")
        lines.append(
            table(
                ("Language", "Solutions Written"),
                list(statistics.language_distribution.items()),
                align_right={1},
            )
        )
        lines.append("")

        if config.show_topics and statistics.topic_distribution:
            lines.append("## Topics Covered")
            lines.append("")
            lines.append(
                table(
                    ("Topic Category", "Problems"),
                    list(statistics.topic_distribution.items()),
                    align_right={1},
                )
            )
            lines.append("")

        if config.show_companies and statistics.company_distribution:
            lines.append("## Targeted Companies")
            lines.append("")
            lines.append(
                table(
                    ("Company Name", "Problems"),
                    list(statistics.company_distribution.items()),
                    align_right={1},
                )
            )
            lines.append("")

        lines.append("## Complete Problem Index")
        lines.append("")
        headers = ("ID", "Problem Title", "Difficulty", "Language")
        rows = []
        sorted_problems = sorted(problems, key=lambda item: item.problem_number)
        for p in sorted_problems:
            folder = p.folder.as_posix() if p.folder else f"{p.difficulty}/{p.title}"
            title_cell = markdown_link(p.title, folder)
            rows.append((p.problem_number, title_cell, difficulty_indicator(p.difficulty), p.language))
        lines.append(table(headers, rows, align_right={0}))

        return "\n".join(lines).rstrip() + "\n"

    def generate_topic_page(
        self,
        topic_name: str,
        problems: Sequence[ProblemMetadata],
        config: DocumentationConfig,
    ) -> str:
        items: list[str] = []
        for problem in sorted(problems, key=lambda p: (p.problem_number, p.title)):
            folder = problem.folder.as_posix() if problem.folder else f"{problem.difficulty}/{problem.title}"
            relative_target = f"../{folder}"
            items.append(f"#{problem.problem_number} {markdown_link(problem.title, relative_target)} [{problem.difficulty}]")

        problem_list = unordered_list(items) if items else "No solved problems for this topic."
        return (
            f"# Topic: {topic_name}\n\n"
            f"**Total Problems Solved**: {len(problems)}\n\n"
            f"## Problem List\n\n"
            f"{problem_list}\n"
        )
